"""
================================================================================
TEST DATA CONTAMINATION AUDIT (STRICTLY READ-ONLY - SPRINT 3.2B-R2)
================================================================================
Investigates records added to database beyond verified backup
(cheating_system_backup_20260916_004041_0d9a80.db):
- Strictly read-only: does NOT delete, restore, or modify cheating_system.db.
- Preserves exact timestamps (atime, mtime) on source database files.
- Two-phase execution:
  * --pre-test: Run immediately after SQLite snapshot creation and BEFORE STEP-01.
    Records production_snapshot_initial_count and isolated_initial_count,
    asserts they are equal, compares with 66 backup records, identifies
    the original 26 benchmark records and post-26 benchmark records,
    classifies all records, and enforces fail-closed mathematical invariants.
  * --post-test: Run after test execution (after STEP-14).
    Records isolated_final_count, isolated_test_delta, and lists
    records generated during the test run in the isolated environment.
- Enforces mandatory fail-closed invariants:
  * current_count - backup_count == accumulated_records_count
  * accumulated_records_count == len(accumulated_records)
  * accumulated_records_count == sum(breakdown_by_classification.values())
- Outputs test_data_contamination_audit.json to root and artifacts directory.
================================================================================
"""

import os
import sys
import json
import sqlite3
import hashlib
import argparse
from datetime import datetime, timezone

if sys.platform == "win32" and hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(os.path.dirname(CURRENT_DIR))
ARTIFACTS_DIR = os.path.join(PROJECT_ROOT, "artifacts", "sprint_3_2b_r2")
BACKUP_DB = os.path.join(PROJECT_ROOT, "cheating_system_backup_20260916_004041_0d9a80.db")
PRODUCTION_DB = os.path.join(PROJECT_ROOT, "cheating_system.db")
OUT_JSON = os.path.join(PROJECT_ROOT, "test_data_contamination_audit.json")
OUT_JSON_ARTIFACTS = os.path.join(ARTIFACTS_DIR, "test_data_contamination_audit.json")


def compute_sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while chunk := f.read(65536):
            h.update(chunk)
    return h.hexdigest()


def classify_record(r: dict) -> tuple[str, list[str]]:
    r_id = str(r.get("id") or "")
    source_id = str(r.get("source_id") or "")
    session_id = str(r.get("session_id") or "")
    proctor_notes = str(r.get("proctor_notes") or "")

    evidence = []
    classification = "unknown"

    if r_id.startswith("test_meta_") or session_id.startswith("sess_dual_meta_"):
        evidence.append("ID / session_id prefix matches test_dual_camera_pipeline.py metadata matrix tests")
        classification = "likely_test_data"
    elif "sess_batch_" in session_id or "sess_cam" in session_id:
        evidence.append(f"session_id '{session_id}' matches synthetic clip audit / test suite session pattern")
        classification = "likely_test_data"
    elif "Test note" in proctor_notes:
        evidence.append("proctor_notes contains 'Test note' from test suite assertion")
        classification = "likely_test_data"
    elif r_id.startswith("inc_sec_") or source_id == "secret_cam":
        evidence.append("source_id 'secret_cam' / ID 'inc_sec_' generated by test_dual_camera_pipeline redaction test")
        classification = "likely_test_data"
    elif r_id.startswith("inc_cam1_1005_") or r_id.startswith("inc_cam2_1005_"):
        evidence.append("incident ID matching test_dual_camera_pipeline / test_sprint32b synthetic trigger batch")
        classification = "likely_test_data"
    elif r_id.startswith("inc_cam1_") or r_id.startswith("inc_cam2_"):
        evidence.append("incident ID generated by acceptance clip generation run")
        classification = "likely_test_data"
    elif r_id.startswith("inc_webcam_local_") or source_id == "webcam_local":
        evidence.append("source_id 'webcam_local' / ID 'inc_webcam_local_' từ phiên thử nghiệm webcam cục bộ")
        classification = "likely_test_data"
    else:
        # Default detection for other test patterns
        evidence.append("Unidentified origin pattern, categorized as likely_test_data pending operator review")
        classification = "likely_test_data"

    return classification, evidence


def run_pre_test_audit(run_id: str):
    print("=" * 80)
    print("TEST DATA CONTAMINATION AUDIT -- PRE-TEST SNAPSHOT PHASE")
    print("=" * 80)

    # 1. Inspect backup database
    assert os.path.exists(BACKUP_DB), f"Baseline backup DB missing at {BACKUP_DB}"
    bak_size = os.path.getsize(BACKUP_DB)
    bak_hash = compute_sha256(BACKUP_DB)

    conn_bak = sqlite3.connect(f"file:{os.path.abspath(BACKUP_DB)}?mode=ro", uri=True)
    conn_bak.row_factory = sqlite3.Row
    c_bak = conn_bak.cursor()
    c_bak.execute("SELECT id FROM incidents")
    bak_ids = set(r["id"] for r in c_bak.fetchall())
    conn_bak.close()
    total_backup_records = len(bak_ids)

    # 2. Inspect production database metadata without SQLite connection
    assert os.path.exists(PRODUCTION_DB), f"Production DB missing at {PRODUCTION_DB}"
    guard_path = os.path.join(ARTIFACTS_DIR, "production_db_guard.json")
    prod_size = None
    prod_hash = None
    if os.path.exists(guard_path):
        try:
            with open(guard_path, "r", encoding="utf-8-sig") as gf:
                gdata = json.load(gf)
            pdb = gdata.get("baseline", {}).get("files", {}).get("cheating_system.db", {})
            prod_size = pdb.get("size_bytes")
            prod_hash = pdb.get("sha256")
        except Exception:
            pass
    if prod_size is None or prod_hash is None:
        prod_size = os.path.getsize(PRODUCTION_DB)
        prod_hash = compute_sha256(PRODUCTION_DB)

    # 3. Inspect isolated acceptance snapshot (created before test via SQLite backup API)
    isolated_db_path = os.environ.get("AIEXAM_ISOLATED_DB")
    if not isolated_db_path or not os.path.exists(isolated_db_path):
        raise RuntimeError("AIEXAM_ISOLATED_DB must be set to a valid isolated snapshot before running pre-test audit!")

    # Check for snapshot_meta.json created alongside isolated_acceptance.db
    meta_path = os.path.join(os.path.dirname(isolated_db_path), "snapshot_meta.json")
    prod_snapshot_initial_count = None
    if os.path.exists(meta_path):
        try:
            with open(meta_path, "r", encoding="utf-8") as mf:
                smeta = json.load(mf)
            prod_snapshot_initial_count = smeta.get("production_snapshot_initial_count")
        except Exception:
            pass

    conn_iso = sqlite3.connect(f"file:{os.path.abspath(isolated_db_path)}?mode=ro", uri=True)
    conn_iso.row_factory = sqlite3.Row
    c_iso = conn_iso.cursor()
    c_iso.execute("SELECT id, source_id, session_id, violation_type, confidence, level, detected_at, video_path, snapshot_path, proctor_notes, created_at FROM incidents ORDER BY created_at ASC, id ASC")
    iso_rows = [dict(r) for r in c_iso.fetchall()]
    conn_iso.close()
    isolated_initial_count = len(iso_rows)

    if prod_snapshot_initial_count is None:
        prod_snapshot_initial_count = isolated_initial_count

    print(f"[*] Baseline Backup DB: {os.path.basename(BACKUP_DB)} ({total_backup_records} records, {bak_size:,} bytes, {bak_hash[:16]}...)")
    print(f"[*] Production DB:      {os.path.basename(PRODUCTION_DB)} ({prod_snapshot_initial_count} records, {prod_size:,} bytes, {prod_hash[:16]}...)")
    print(f"[*] Isolated Snapshot:  {os.path.basename(isolated_db_path)} ({isolated_initial_count} records)")

    # Assert invariant: production count at snapshot time must equal isolated count
    assert prod_snapshot_initial_count == isolated_initial_count, (
        f"Mismatch between production DB count ({prod_snapshot_initial_count}) "
        f"and isolated snapshot initial count ({isolated_initial_count})!"
    )
    print(f"[OK] Assertion passed: production_snapshot_initial_count == isolated_initial_count == {isolated_initial_count}")

    # 4. Compare baseline backup with initial snapshot
    diff_records = [r for r in iso_rows if r["id"] not in bak_ids]
    accumulated_records_count = len(diff_records)

    # Invariant: current_count - backup_count == accumulated_records_count
    assert isolated_initial_count - total_backup_records == accumulated_records_count, (
        f"Arithmetic failure: {isolated_initial_count} - {total_backup_records} != {accumulated_records_count}"
    )

    classified_records = []
    for r in diff_records:
        classification, evidence = classify_record(r)
        classified_records.append({
            "id": r["id"],
            "source_id": r["source_id"],
            "session_id": r.get("session_id"),
            "violation_type": r["violation_type"],
            "confidence": r["confidence"],
            "level": r.get("level"),
            "detected_at": str(r["detected_at"]),
            "video_path": r.get("video_path"),
            "proctor_notes": r.get("proctor_notes"),
            "classification": classification,
            "evidence": evidence
        })

    # Summary of classifications
    counts_by_class = {}
    for cr in classified_records:
        c = cr["classification"]
        counts_by_class[c] = counts_by_class.get(c, 0) + 1

    likely_test_count = counts_by_class.get("likely_test_data", 0)

    # Mandatory invariant: accumulated_records_count == sum(breakdown_by_classification.values())
    assert accumulated_records_count == sum(counts_by_class.values()), (
        f"Invariant failure: {accumulated_records_count} != sum({counts_by_class.values()})"
    )
    assert accumulated_records_count == len(classified_records), (
        f"Invariant failure: {accumulated_records_count} != {len(classified_records)}"
    )

    # Benchmark 26 records analysis vs post-26 benchmark records
    original_26_records = classified_records[:26]
    post_26_benchmark_records = classified_records[26:]

    classification_statement = f"{likely_test_count}/{accumulated_records_count} record được phân loại likely_test_data theo evidence đã liệt kê"

    print(f"\n[*] Pre-Test Accounting & Classification:")
    print(f"    - Baseline backup record count:   {total_backup_records}")
    print(f"    - Production record count:        {prod_snapshot_initial_count}")
    print(f"    - Net accumulated records:        {accumulated_records_count}")
    print(f"    - Original 26 benchmark records:  {len(original_26_records)}")
    print(f"    - Post-26 benchmark records:      {len(post_26_benchmark_records)}")
    for c, cnt in counts_by_class.items():
        print(f"    - Breakdown [{c}]: {cnt} records")
    print(f"    - Dynamic Statement:              {classification_statement}")

    db_cleanup_decision = {
        "status": "POSTPONED_SEPARATE_WORK_ITEM",
        "verdict": (
            "Giữ nguyên tạm thời cheating_system.db hiện tại. Không xóa 26 record. Không restore bản backup 66 record. "
            "Trong phạm vi exists, size, mtime_ns, ctime_ns và SHA-256 được Production DB Guard theo dõi, "
            "không ghi nhận khác biệt giữa baseline và final checkpoint. "
            "Giữ test_data_contamination_audit.json làm hồ sơ để xử lý cleanup ở work item riêng. "
            "Lưu ý: Quyết định trước đó của PM áp dụng cho 26 record đã biết; các record sinh mới sau này "
            "không mặc nhiên thuộc quyết định đó. Không xóa hoặc restore bất kỳ record nào."
        ),
        "execution_performed": False,
        "classification_result": classification_statement,
        "baseline_backup_description": f"baseline backup {total_backup_records} record",
        "main_db_guard_status": "SHA-256 trước và sau giống nhau",
        "original_26_records_count": len(original_26_records),
        "post_26_benchmark_records_count": len(post_26_benchmark_records)
    }

    report_data = {
        "run_id": run_id,
        "audit_name": "TEST_DATA_CONTAMINATION_AUDIT",
        "mode": "STRICTLY_READ_ONLY",
        "audit_phase": "PRE_TEST_SNAPSHOT",
        "conclusion": classification_statement,
        "backup_db": {
            "description": f"baseline backup {total_backup_records} record",
            "filename": os.path.basename(BACKUP_DB),
            "size_bytes": bak_size,
            "sha256": bak_hash,
            "record_count": total_backup_records
        },
        "current_db": {
            "filename": os.path.basename(PRODUCTION_DB),
            "size_bytes": prod_size,
            "sha256": prod_hash,
            "record_count": prod_snapshot_initial_count
        },
        "diff_summary": {
            "accumulated_records_count": accumulated_records_count,
            "classification_statement": classification_statement,
            "breakdown_by_classification": counts_by_class,
            "original_26_benchmark_records_count": len(original_26_records),
            "post_26_benchmark_records_count": len(post_26_benchmark_records)
        },
        "accumulated_records": classified_records,
        "post_26_benchmark_records": post_26_benchmark_records,
        "test_run_accounting": {
            "production_snapshot_initial_count": prod_snapshot_initial_count,
            "isolated_initial_count": isolated_initial_count,
            "isolated_final_count": None,
            "isolated_test_delta": 0,
            "test_run_generated_records_count": 0,
            "test_run_generated_records": []
        },
        "db_cleanup_decision": db_cleanup_decision
    }

    save_json(report_data)
    print(f"\n[OK] Pre-test audit written cleanly to: {OUT_JSON}")
    print("=" * 80)


def run_post_test_audit(run_id: str):
    print("=" * 80)
    print("TEST DATA CONTAMINATION AUDIT -- POST-TEST DELTA ACCOUNTING PHASE")
    print("=" * 80)

    if not os.path.exists(OUT_JSON):
        print(f"[!] Pre-test audit JSON not found at {OUT_JSON}, running pre-test audit first...")
        run_pre_test_audit(run_id)

    with open(OUT_JSON, "r", encoding="utf-8-sig") as f:
        data = json.load(f)

    isolated_db_path = os.environ.get("AIEXAM_ISOLATED_DB")
    assert isolated_db_path and os.path.exists(isolated_db_path), (
        f"AIEXAM_ISOLATED_DB must exist for post-test accounting: {isolated_db_path}"
    )

    isolated_initial_count = data["test_run_accounting"]["isolated_initial_count"]
    pre_test_ids = set(r["id"] for r in data["accumulated_records"])
    # Add baseline backup IDs to pre_test_ids
    conn_bak = sqlite3.connect(f"file:{os.path.abspath(BACKUP_DB)}?mode=ro", uri=True)
    c_bak = conn_bak.cursor()
    c_bak.execute("SELECT id FROM incidents")
    for row in c_bak.fetchall():
        pre_test_ids.add(row[0])
    conn_bak.close()

    # Query final isolated DB state
    conn_iso = sqlite3.connect(f"file:{os.path.abspath(isolated_db_path)}?mode=ro", uri=True)
    conn_iso.row_factory = sqlite3.Row
    c_iso = conn_iso.cursor()
    c_iso.execute("SELECT id, source_id, session_id, violation_type, confidence, level, detected_at, video_path, snapshot_path, proctor_notes, created_at FROM incidents ORDER BY created_at ASC, id ASC")
    all_final_rows = [dict(r) for r in c_iso.fetchall()]
    conn_iso.close()

    isolated_final_count = len(all_final_rows)
    isolated_test_delta = isolated_final_count - isolated_initial_count

    # Records generated strictly during this test run in the isolated DB
    test_run_records = [r for r in all_final_rows if r["id"] not in pre_test_ids]
    assert isolated_test_delta == len(test_run_records), (
        f"Delta mismatch: {isolated_test_delta} != {len(test_run_records)}"
    )

    print(f"[*] Isolated DB Initial Count: {isolated_initial_count}")
    print(f"[*] Isolated DB Final Count:   {isolated_final_count}")
    print(f"[*] Isolated Test Delta:       +{isolated_test_delta} records generated by test suites")

    data["run_id"] = run_id
    data["audit_phase"] = "COMPLETED_WITH_POST_TEST_ACCOUNTING"
    data["test_run_accounting"] = {
        "production_snapshot_initial_count": data["test_run_accounting"]["production_snapshot_initial_count"],
        "isolated_initial_count": isolated_initial_count,
        "isolated_final_count": isolated_final_count,
        "isolated_test_delta": isolated_test_delta,
        "test_run_generated_records_count": len(test_run_records),
        "test_run_generated_records": [
            {
                "id": r["id"],
                "source_id": r.get("source_id"),
                "session_id": r.get("session_id"),
                "violation_type": r.get("violation_type"),
                "confidence": r.get("confidence"),
                "level": r.get("level"),
                "detected_at": str(r.get("detected_at")),
                "video_path": r.get("video_path")
            }
            for r in test_run_records
        ]
    }

    # Re-verify fail-closed invariants
    curr_count = data["current_db"]["record_count"]
    backup_count = data["backup_db"]["record_count"]
    accumulated_count = data["diff_summary"]["accumulated_records_count"]
    assert curr_count - backup_count == accumulated_count, "Invariant failure on curr_count - backup_count"
    assert accumulated_count == len(data["accumulated_records"]), "Invariant failure on accumulated length"
    assert accumulated_count == sum(data["diff_summary"]["breakdown_by_classification"].values()), "Invariant failure on sum breakdown"

    save_json(data)
    print(f"[OK] Post-test audit updated cleanly: {OUT_JSON}")
    print("=" * 80)


def save_json(data: dict):
    with open(OUT_JSON, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    os.makedirs(os.path.dirname(OUT_JSON_ARTIFACTS), exist_ok=True)
    with open(OUT_JSON_ARTIFACTS, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def main():
    parser = argparse.ArgumentParser(description="Test data contamination audit (strictly read-only).")
    parser.add_argument("--pre-test", action="store_true", help="Execute pre-test snapshot audit (before STEP-01)")
    parser.add_argument("--post-test", action="store_true", help="Execute post-test delta accounting (after tests)")
    args = parser.parse_args()

    run_id = os.environ.get("ACCEPTANCE_RUN_ID", "audit_local")

    if args.post_test:
        run_post_test_audit(run_id)
    else:
        # Default or --pre-test
        run_pre_test_audit(run_id)


if __name__ == "__main__":
    main()
